import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#faf3e1]">
        <Header />
        <div className="bg-[#faf3e1] mx-auto max-w-6xl">
          {children}
          {modal}
        </div>
      </body>
    </html>
  );
}
